### ISSUE TITLE
Error when installing tools

### ISSUE THREAD

**Issue by Zer0G0ld** [Ahosall/UniTools#1]
Whenever I try to install a tool, I receive this error:

```
=====] CLONE
fatal: destination path 'gasmask' already exists and is not an empty directory.
sh: 1: cd: can't cd to gasmask

=====] CLONED

Traceback (most recent call last):
File "/home/theuzgod/UniTools/app.py", line 73, in <module>
func = main()
^^^^^^
File "/home/theuzgod/UniTools/app.py", line 54, in main
elif choice == 1: return infoGathering.menu()
^^^^^^^^^^^^^^^^^^^^
File "/home/theuzgod/UniTools/src/tools/infoGathering.py", line 409, in menu
elif int(choice) == 10: return OSIF()
^^^^^^
File "/home/theuzgod/UniTools/src/tools/infoGathering.py", line 117, in OSIF
cc(('infoGathering', 'OSIF'), 'Infosploit has been successfully cloned or installed... To access it go to the tools folder.')
File "/home/theuzgod/UniTools/src/utils/functions.py", line 92, in cc
updateTool(tool, 'GREEN')
File "/home/theuzgod/UniTools/src/utils/configs.py", line 27, in updateTool
toolsStts[tools[0]][tools[1]]['Locale'] = configs[tools]
~~~~~~~^^^^^^^
KeyError: ('infoGathering', 'OSIF')
```

How do I solve this?

**Comment by Ahosall** [comment]
Hello! Thanks for reporting, I'll be working on a new, improved and complete version. This will be fixed during construction.

Thank you again!

![UniTools v2023.08](https://github.com/Ahosall/UniTools/assets/49027157/3eabcb30-9de4-4ed0-81c5-491fb23deae4)
